#!/usr/bin/env bash

alias h='history'
alias hs='history | grep -i '

### directories and listings
alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'

alias dl="cd ~/Downloads"
alias p="cd ~/Projects"
alias w="cd /Work/"
alias gp="cd $GOPATH"

alias ls='ls'
alias ll='ls -ahl'

### git and related
alias g='git'
alias s='git status'
alias a='git add'
alias c='git commit'
alias cm='git commit -m'
alias d='git diff'
alias co='git checkout'
# __git_complete gco _git_checkout
alias l="git log --graph --abbrev-commit --decorate --format=format:'%C(yellow)%h%C(reset) - %C(normal)%aD%C(reset) %C(green)(%ar)%C(reset)%C(yellow)%d%C(reset)%n''          %C(bold normal)%s%C(reset) %C(cyan)- %an%C(reset)'"

### tools
alias v='vim'
alias pw='openssl rand -base64 16'

### system
# IP addresses
function ips() {
  echo "Public: $(dig +short myip.opendns.com @resolver1.opendns.com)"
  echo "Local: $(ipconfig getifaddr en0)"

  if [[ $OSTYPE == darwin* ]]; then
    echo "Gateway: $(route -n get default | awk '/gateway/ {print $2}')"
  fi
}
alias ips='ips'

### OSX
if [[ $OSTYPE == darwin* ]]; then
  alias update='sudo softwareupdate -i -a; brew update; brew upgrade --all; brew cleanup'
  alias flushdns='sudo killall -HUP mDNSResponder'

  # Hide/show all desktop icons (useful when presenting)
  alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
  alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
fi
