#!/usr/bin/env bash

### TODO: should be removed soon
alias dev-01-up='VBoxManage startvm dev-01 --type headless'
alias dev-01-pause='VBoxManage controlvm dev-01 pause'
alias dev-01-resume='VBoxManage controlvm dev-01 resume'
alias dev-01-down='VBoxManage controlvm dev-01 acpipowerbutton'
alias dev-01-ip='VBoxManage guestproperty enumerate dev-01 | grep IP | egrep -o "\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}"'
alias sr-dev-01='ssh root@$(dev-01-ip)'
alias s-dev-01='ssh denys@$(dev-01-ip)'
### END: should be removed soon

alias h='history'
alias hs='history | grep -i '

### directories and listings
alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'

alias dl="cd ~/Downloads"
alias d="cd ~/Desktop"
alias p="cd ~/Projects"
alias w="cd /Work/"

alias ls='ls'
alias ll='ls -ahl'

### git and related
alias gs='git status '
alias ga='git add '
alias gc='git commit'
alias gd='git diff'
alias gco='git checkout'
# __git_complete gco _git_checkout
alias gl="git log --graph --abbrev-commit --decorate --format=format:'%C(yellow)%h%C(reset) - %C(normal)%aD%C(reset) %C(green)(%ar)%C(reset)%C(yellow)%d%C(reset)%n''          %C(bold normal)%s%C(reset) %C(cyan)- %an%C(reset)' --all"
alias gmo='MASTER=`git rev-parse --abbrev-ref HEAD` && git checkout online && git merge $MASTER && git push && git checkout $MASTER'
alias gmp='MASTER=`git rev-parse --abbrev-ref HEAD` && git checkout production && git merge $MASTER && git push && git checkout $MASTER'

### system
# IP addresses
function ips() {
  echo "Public: $(dig +short myip.opendns.com @resolver1.opendns.com)"
  echo "Local: $(ipconfig getifaddr en0)"

  if [[ $OSTYPE == darwin* ]]; then
    echo "Gateway: $(route -n get default | awk '/gateway/ {print $2}')"
  fi
}
alias ips='ips'

### OSX
if [[ $OSTYPE == darwin* ]]; then
  alias update='sudo softwareupdate -i -a; brew update; brew upgrade --all; brew cleanup'
  alias flushdns='sudo killall -HUP mDNSResponder'

  # Hide/show all desktop icons (useful when presenting)
  alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
  alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
fi