#!/usr/bin/env bash

alias h='history'
alias hs='history | grep -i '

### directories and listings
alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'

alias dl="cd ~/Downloads"
alias p="cd ~/projects"

alias ls='ls'
alias l='ls -ahl'
alias ll='ls -hl'

### tools
alias pw='openssl rand -base64 32'

### system
# IP addresses
function ips() {
  echo "Public: $(dig +short myip.opendns.com @resolver1.opendns.com)"
  echo "Local: $(ipconfig getifaddr en0)"

  if [[ $OSTYPE == darwin* ]]; then
    echo "Gateway: $(route -n get default | awk '/gateway/ {print $2}')"
  fi
}
alias ips='ips'

### OSX
if [[ $OSTYPE == darwin* ]]; then
  alias update='sudo softwareupdate -i -a; brew update; brew upgrade --all; brew cleanup'
  alias flushdns='sudo killall -HUP mDNSResponder'
  alias fixvideo='sudo killall VDCAssistant'

  # Hide/show all desktop icons (useful when presenting)
  alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
  alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
fi
