#!/usr/bin/env bash

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# get absolute path for ienv files
IENV=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )


# load components
source $IENV/env
source $IENV/bash-history
source $IENV/bash-completion
source $IENV/aliases
source $IENV/coloring
source $IENV/prompt
source $IENV/ssh
source $IENV/aws
source $IENV/python
source $IENV/rust

for f in $IENV/site/*; do source $f; done
